### Listar os funcionários
GET https://localhost:5001/api/funcionario/listar

### Buscar um funcionário
GET https://localhost:5001/api/funcionario/buscar/123

### Cadastrar um funcionário
POST https://localhost:5001/api/funcionario/cadastrar
Content-Type: application/json

{
    "nome" : "Diogo Steinke Deconto",
    "cpf" : "12312312312",    
    "email" : "asd@asd",
    "salario" : 1000
}

### Deletar um funcionário
DELETE https://localhost:5001/api/funcionario/deletar/9

### Alterar um funcionário
PATCH https://localhost:5001/api/funcionario/alterar
Content-Type: application/json

{
    "funcionarioid" : 10,
    "nome" : "diogo deconto modificado",
    "cpf" : "123"
}